aho_datacapturetool/urls.py
"""
Global DCT App URL route Configurations points the URL patterns to views
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import path,include,re_path
from home import views
from django.conf.urls.i18n import i18n_patterns #added
from django.views.static import serve # hack to support display of uploaded files
from django.conf import settings # Facilitate viewing on browser pdf reader
from django.conf.urls.static import static # Facilitate display of static assets
from django.conf.urls import handler404,handler500 # display custom 404 error page
from rest_framework_simplejwt.views import (
    TokenObtainPairView, TokenRefreshView,)
from rest_framework.documentation import (
    include_docs_urls, get_schemajs_view)
from rest_framework_swagger.views import get_swagger_view

from rest_framework.authtoken.views import obtain_auth_token

admin.autodiscover() # Autoloads the custom login page instead of auth.admin view
admin.site.login = login_required(admin.site.login)

admin.site.site_header="DCT Admin"
admin.site.site_title="DCT Admin"
admin.site.index_title="DCT Admin"

schema_view = get_swagger_view(title='Data Capture Tool API Endpoints')

api_patterns = [
    path('', schema_view, name='swagger_docs'), # Load swagger docs page 3/5/21
    # path('', include('router.urls',namespace='api')),
    path('', include(('regions.urls','regions'),namespace='regions')),
    path('', include(('indicators.urls','indicators'),namespace='indicators')),
    path('', include(('publications.urls','publications'),namespace='publications')),
    path('', include(('elements.urls', 'elements'), namespace='elements')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('', include(('facilities.urls', 'facilities'), namespace='facilities')),
    path('', include(('health_workforce.urls','health_workforce'),
        namespace='health_workforce')),
    path('', include(('health_services.urls', 'health_services'),
        namespace='health_services')),
]

"""
This pattern was added on 25/10/2020 to allow setting of the base/root URL to
 include language selected from the login form once the used selects en, fror pt
 """
urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')), #Important for language selection
]

urlpatterns += i18n_patterns ( # must be python immutable list () and not []

   path('', views.index, name='index'),
    path('admin/', admin.site.urls,name='dashboard'),
    path('accounts/login/', views.login_view, name='login'),

    path('datawizard/', include('data_wizard.urls')), #for data import wizard
    #Daniel support to validate A->B->C pupolated selection in facility services
    path('chaining/', include('smart_selects.urls')),
   #Reset and Changepassword urls
    path('password-reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    path('admin/quality/',include('data_quality.urls',namespace='data_quality')),

   # API-based URL patterns for hitting KHRO endpoints for consuming data in JSON
    path('api/', include((api_patterns, 'api'), namespace='api')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api-auth/', include('rest_framework.urls')), # For browsable REST API
    path('api/docs/', include_docs_urls(title='iAHO-DCT',public=False)),
    path('api/schema/', get_schemajs_view(title='iAHO-DCT', public=False)),
    path('api/auth-token/', obtain_auth_token),

    # Route that allows display of uploaded files when Debug=False in settings.py
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    prefix_default_language=False # Hide default language code (en) on all urls

)
# Routes for error handlers served by home view and templates/home/errors
handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'

authentication/urls.py
from django.urls import re_path, path
from authentication.views import (microsoft_login,microsoft_logout,callback,)

app_name = 'microsoft_authentication'#renamed authntication app to match callbacks

urlpatterns = [
    path('login', microsoft_login, name="microsoft_authentication_login"),
    path('logout', microsoft_logout, name="microsoft_authentication_logout"),
    path('callback', callback, name="microsoft_authentication_callback"),
]

home/urls.py
from rest_framework.routers import SimpleRouter
from home import views

router = SimpleRouter()

router.register(
    r'disagregation_categories',views.StgDisagregationCategoryViewSet,
    "disagregation_category",)
router.register(
    r'disagregation_options',views.StgDisagregationOptionsViewSet,
    "disagregation_option")
router.register(
    r'data_sources', views.StgDatasourceViewSet, "data_source")
router.register(
    r'value_types', views.StgValueDatatypeViewSet, "value_type")
router.register(
    r'measure_types', views.StgMeasuremethodViewSet, "measure_type")
urlpatterns = router.urls

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from rest_framework import viewsets
from rest_framework import (generics,permissions,renderers,)
from rest_framework.decorators import api_view # new
from rest_framework.response import Response # new
from rest_framework.reverse import reverse # new

from commoninfo.permissions import IsOwnerOrReadOnly,CustomDjangoModelPermissions
from . serializers import (StgDatasourceSerializer,
    StgDisagregationOptionsSerializer,StgDisagregationCategorySerializer,
    StgValueDatatypeSerializer,StgMeasuremethodSerializer,)
from .models import (StgDatasource,StgCategoryParent, StgCategoryoption,
    StgValueDatatype,StgMeasuremethod,)
from django.conf import settings


class StgDisagregationCategoryViewSet(viewsets.ModelViewSet):
    serializer_class = StgDisagregationCategorySerializer
    permission_classes = (permissions.IsAuthenticated,
        CustomDjangoModelPermissions,)

    def get_queryset(self):
        language = self.request.LANGUAGE_CODE # get the en, fr or pt from the request
        return StgCategoryParent.objects.filter(
            translations__language_code=language).order_by(
            'translations__name').distinct()

class StgDisagregationOptionsViewSet(viewsets.ModelViewSet):
    serializer_class = StgDisagregationOptionsSerializer
    permission_classes = (permissions.IsAuthenticated,
        CustomDjangoModelPermissions,)

    def get_queryset(self):
        language = self.request.LANGUAGE_CODE # get the en, fr or pt from the request
        return StgCategoryoption.objects.filter(
            translations__language_code=language).order_by(
            'translations__name').distinct()


class StgDatasourceViewSet(viewsets.ModelViewSet):
    queryset = StgDatasource.objects.all()
    serializer_class = StgDatasourceSerializer
    permission_classes = (permissions.IsAuthenticated,
        CustomDjangoModelPermissions,)

    def get_queryset(self):
        language = self.request.LANGUAGE_CODE # get the en, fr or pt from the request
        return StgDatasource.objects.filter(
            translations__language_code=language).order_by(
            'translations__name').distinct()


class StgValueDatatypeViewSet(viewsets.ModelViewSet):
    serializer_class = StgValueDatatypeSerializer
    permission_classes = (permissions.IsAuthenticated,
        CustomDjangoModelPermissions,)

    def get_queryset(self):
        language = self.request.LANGUAGE_CODE # get the en, fr or pt from the request
        return StgValueDatatype.objects.filter(
            translations__language_code=language).order_by(
            'translations__name').distinct()


class StgMeasuremethodViewSet(viewsets.ModelViewSet):
    serializer_class = StgMeasuremethodSerializer
    permission_classes = (permissions.IsAuthenticated,
        CustomDjangoModelPermissions,)

    def get_queryset(self):
        language = self.request.LANGUAGE_CODE # get the en, fr or pt from the request
        return StgMeasuremethod.objects.filter(
            translations__language_code=language).order_by(
            'translations__name').distinct()

#This code is for the login page
context = {}
def index(request):
    return render(request, 'index.html', context=context)

def login_view(request):
    if not request.POST.get('username') or not request.POST.get('password'):
        return render(request, 'index.html', context=context)
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # request.session['language'] = request.POST['language']
        return redirect('admin:index') # Changed 25/10/2020 for multi-lingo login
    else:
        return render(
            request, 'index.html', {
                    'error_message': 'Login Failed! \
                    Please enter Valid Username and Password.', })

# Methods for custom error handlers that serve htmls in templates/home/errors
def handler404(request, exception):
    context = {}
    response = render(request, "errors/404.html", context=context)
    response.status_code = 404
    return response

def handler500(request):
    context = {}
    response = render(request, "errors/500.html", context=context)
    response.status_code = 500
    return response

home/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'ahocss/index.css' %}" />
    <link rel="stylesheet" href="{% static 'dataframe.css' %}" />
    <title>Data Capture Tool</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
</head>
<body>
    <div class="container-fluid">
        <div>
            <h2 class="text-white text-center">{% block title %}{% endblock %}</h2>
            <div class="card p-5">
                <div class="text-center">
                  <a href="{% url 'login' %}">
                    <img class = "img-fluid" src="{% static "iaho_logo.png" %}"
                    alt="Login Screen">
                  </a>
                </div>
                {% block content %}
                {% endblock %}
            </div>

        </div>
    </div>
</body>
</html>

home/templates/index.html
{% load static %} <!--load logo and css files from the static subdirector-->
{% load i18n %} <!--Language translation to support english, French and Portuguese-->
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title> Data Capture Tool</title>
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" />
		<!-- Bootstrap CSS modified to be loaded from static subdirectory-->
		<link rel="stylesheet" href="{% static 'ahocss/bs/css/flatly.min.css' %}" />
		<link rel="stylesheet" href="{% static 'ahocss/styles.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">
	<body>
		<div class="container-fluid" id="wrapper">
		<p class = body_title> {% trans "DCT Training Tool" %}</p>
			<div class="row">
				<div class="col-lg-4 col-lg-offset-4" id="content">
					<div class="row t10">
						<div class="col-lg-12">
							<form id="login-form" method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <table class="table">
									<div>
										<img src="{% static "iaho_logo.png" %}" class="logo">
									</div>
									{% if error_message %}
									<div class="login-valivation alert alert-danger">
										<p>
										{{error_message}}
										</p>
									</div>
									{% endif %}
										<tr>
                        <td>
													<label for="id_username" class="labels">{% trans "Username" %}</label>
												</td>
                        <td>
													<input type="text" name="username" class="form-control" required="" placeholder="myemail@who.int">
												</td>
                    </tr>

										<tr>
                        <td>
													<label for="id_password" class="labels">{% trans "Password" %} </label>
												</td>
                        <td>
													<input type="password" name="password" class="form-control" required="" placeholder="Mysecret.pass">
												</td>
                    </tr>
                </table>

                <input type="submit" value={% trans "Login" %} class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
					  </form>
						<h5 class="labels"> {% trans "Choose language" %} </h5>
						<form action="{% url 'set_language' %}" method="post">
							{% csrf_token %}
							<input name="next" type="hidden" value="{{ redirect_to }}">
							<select name="language" onChange="form.submit();";>
									{% get_current_language as LANGUAGE_CODE %}
									{% get_available_languages as LANGUAGES %}
									{% get_language_info_list for LANGUAGES as languages %}
									{% for language in languages %}
											<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
													{{ language.name_local|title }} ({{ language.code }})
											</option>
									{% endfor %}
							</select>
						</form>

						<div id="password-reset-link">
								<a href="{% url 'password_reset' %}">{% trans "Forgot your password?" %}</a>
						</div>

						</div>
					</div>

				</div>

			</div>
			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
					</div>
				</div>
			</footer>
		</div>

	</body>
</html>

home/templates/indexx.html
{% load static %} <!--load logo and css files from the static subdirector-->
{% load i18n %} <!--Language translation to support english, French and Portuguese-->
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title> Data Capture Tool</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
		<!-- Bootstrap CSS modified to be loaded from static subdirectory-->
		<link rel="stylesheet" href="{% static 'ahocss/bs/css/flatly.min.css' %}" />
		<link rel="stylesheet" href="{% static 'ahocss/styles.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">
	<body>
		<div class="container-fluid" id="wrapper">
		<p class = body_title> {% trans "iAHO Data Capture Tool" %}</p>
			<div class="row">
				<div class="col-lg-4 col-lg-offset-4" id="content">
					<div class="row t10">
						<div class="col-lg-12">
							<form id="login-form" method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <table class="table">
									<div>
										<img src="{% static "aho_en.png" %}" class="logo">
									</div>
									{% if error_message %}
									<div class="login-valivation alert alert-danger">
										<p>
										{{error_message}}
										</p>
									</div>
									{% endif %}
										<tr>
                        <td>
													<label for="id_username" class="labels">{% trans "Username" %}</label>
												</td>
                        <td>
													<input type="text" name="username" class="form-control" required="" placeholder="myemail@who.int">
												</td>
                    </tr>

										<tr>
                        <td>
													<label for="id_password" class="labels">{% trans "Password" %} </label>
												</td>
                        <td>
													<input type="password" name="password" class="form-control" required="" placeholder="Mysecret.pass">
												</td>
                    </tr>
                </table>

                <input type="submit" value={% trans "Login" %} class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
					  </form>
						<h5 class="labels"> {% trans "Choose language" %} </h5>
						<form action="{% url 'set_language' %}" method="post">
							{% csrf_token %}
							<input name="next" type="hidden" value="{{ redirect_to }}">
							<select name="language" onChange="form.submit();";>
									{% get_current_language as LANGUAGE_CODE %}
									{% get_available_languages as LANGUAGES %}
									{% get_language_info_list for LANGUAGES as languages %}
									{% for language in languages %}
											<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
													{{ language.name_local|title }} ({{ language.code }})
											</option>
									{% endfor %}
							</select>
						</form>

						<div id="password-reset-link">
								<a href="{% url 'password_reset' %}">{% trans "Forgot your password?" %}</a>
						</div>

						</div>
					</div>

				</div>

			</div>
			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
					</div>
				</div>
			</footer>
		</div>

	</body>
</html>

home/templates/login.html
<!-- templates/login.html -->
 {% extends 'base.html' %}
 {% load i18n %} <!--Language translation to support english, French and Portuguese-->
 {% block title %}Data Capture Tool {% endblock %}
 {% block content %}
 <div class="row">
     <div class="col-md-8 mx-auto social-container my-2 order-md-1">
         <button class="btn btn-primary mb-2">
             <a href="{% url 'microsoft_authentication:microsoft_authentication_login' %}">
               {%trans "Login with Microsoft Azure" %}
             </a>
         </button>
     </div>
 </div>
 <h5 class="labels"> {% trans "Language/Langue/Idioma" %} </h5>
<form action="{% url 'set_language' %}" method="post">
  {% csrf_token %}
  <input name="next" type="hidden" value="{{ redirect_to }}">
  <select class="custom-select" name="language" onChange="form.submit();";>
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as languages %}
      {% for language in languages %}
          <option value="{{ language.code }}"
              {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local|title }} ({{ language.code }})
          </option>
      {% endfor %}
  </select>
</form>
 {% endblock %}

home/templates/logout.html
{% extends 'base.html' %}
{% load i18n %} <!--Language translation to support english, French and Portuguese-->
{% block title %}
    Signed out DCT {{ block.super }}
{% endblock %}

{% block content %}
    <div class="content">
        <div class="section-inner clearfix">
        <p>You are logged out.
          <a href="{% url 'microsoft_authentication:microsoft_authentication_login' %}">
            Click Here</a> or <strong>iAHO</strong> to signin again.</p>
        </div>
    </div>

{% endblock %}